---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

# Check the swift_hash_path_* variables haven't changed
- include: swift_check_hashes.yml
  static: no
  when:
    - "not swift_force_change_hashes | bool"
  tags:
    - swift-config

- include: swift_pre_install.yml
  static: no
  when:
    - "swift_do_setup | bool"
    - "'swift_all' in group_names"
  tags:
    - swift-install

- include: swift_install.yml
  static: no
  when:
    - "swift_do_setup | bool"
    - "'swift_all' in group_names"
  tags:
    - swift-install

- include: swift_post_install.yml
  static: no
  when:
    - "swift_do_setup | bool"
    - "'swift_all' in group_names"
  tags:
    - swift-config

- include: swift_calculate_addresses.yml
  static: no
  when:
    - "'swift_hosts' in group_names"
  tags:
    - always

- include: swift_storage_hosts.yml
  static: no
  when:
    - "swift_do_setup | bool"
    - "'swift_hosts' in group_names"
  tags:
    - swift-config

- include: swift_proxy_hosts.yml
  static: no
  when:
    - "swift_do_setup | bool"
    - "'swift_proxy' in group_names"
  tags:
    - swift-config

- include: "swift_init_{{ ansible_service_mgr }}.yml"
  static: no
  tags:
    - swift-config

- include: swift_service_setup.yml
  static: no
  when:
    - "swift_do_setup | bool"
    - '"keystoneauth" in swift_middleware_list'
    - "inventory_hostname == ((groups['swift_all'] | intersect(ansible_play_hosts)) | list)[0]"
  tags:
    - swift-config

# When doing rolling upgrades, we addres a single node at a time
# In these instances, the variables necessary to do sync/key work aren't available,
# nor is the sync/key updating necessary. Thus, skip that work on upgrade.
- name: Check if installing or upgrading
  set_fact:
    need_sync: True
  when:
    - ansible_local is defined
    - ('swift' not in ansible_local['openstack_ansible'] or
       'venv_tag' not in ansible_local['openstack_ansible']['swift'] or
       ansible_local['openstack_ansible']['swift']['venv_tag'] == swift_venv_tag)
  tags: swift-config

- include: swift_key_setup.yml
  static: no
  when:
    - "swift_do_sync | bool"
    - "need_sync is defined"
  tags:
    - swift-config

- include: swift_rings.yml
  static: no
  when:
    - "swift_do_sync | bool"
    - "need_sync is defined"
  tags:
    - swift-config
    - swift-rings

- name: Flush handlers
  meta: flush_handlers
